### DISCUSSION TITLE
How to migrate ACME installed with script to Docker ?

### DISCUSSION THREAD

**Discussion by Carlos920** [acmesh-official/acme.sh#5272] [Q&A]
How to migrate ACME installed with script to Docker ?

Is it similar to this ?
What more operations are needed?
```
services:
  acme-sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    volumes:
      - ~/.acme.sh:/acme.sh
    network_mode: host
    command: daemon
    stdin_open: true
    tty: true
    restart: no
```
