### ISSUE TITLE
部署、签发、守护，用 docker 能不能一步到位?

### ISSUE THREAD

**Issue by tanst** [acmesh-official/acme.sh#3564]
现在一般都用 docker 了，能不能用 docker-compose 一开始运行就部署并开启守护，而不需要再分 3 步进行
```
acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    command: daemon
    volumes:
      - /docker/acme.sh:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - TZ=Asia/Shanghai
      - CF_Token="q7Rv04V956gfdfGTaLk1JzceuPL1wQzpoN13Vz"
      - CF_Account_ID="cdf270bhgfg54j3baeb1e99cd7dc3"
      - DEPLOY_DOCKER_CONTAINER_LABEL=acme=nginx
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE="/config/keys/cert.key"
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/config/keys/cert.crt"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="nginx -c /config/nginx/nginx.conf -s reload"
    restart: unless-stopped
```
