### ISSUE TITLE
Issue certificates in nginx mode with nginx running in a container

### ISSUE THREAD

**Issue by leonardospeca** [acmesh-official/acme.sh#3705]
Hi, I'm running nginx in a docker container, I use it to redirect request like
```
rest.serverip.com to serverip.com:8001
ws.serverip.com to serverip.com:8002
turn.serverip.com to serverip.com:8003
```
I would like to use the `--nginx` option to issue certificates without have to use the acme-challange and write files on the web root, but when I execute
```
acme.sh --issue --nginx -d serverip.com -d rest.serverip.com -d ws.serverip.com -d turn.serverip.com -w /home/user/certs
```
I get the `nginx command is not found.` error.
Nginx command is accessible doing `docker-compose exec -T nginx nginx` where the first `nginx` is the container name and the second one is the command. So the command `docker-compose exec -T nginx nginx -v` return me the version of the nginx in the docker container.

It is possible to do with this configuration?
Before that I successfully issued certificates with the standard mode, but every time I need to change the nginx configuration to allow the acme challange on the webroot and then put it back again.

**Comment by kompolom** [comment]
I waste many time to deal with it, and my solution is use [traefik](https://traefik.io/traefik/) as proxy for all projects on the server. Traefik can manage SSL certificates by himself. We use this opportunity for simple configured projects with SSL termination.
For projects with more complicated SSL config we passthrough encrypted traffic to project service endpoint (nginx) witch configured to bypass acme challenges to acme.sh service.
That is nginx service config part:

```
server {
    listen 80;
    server_name  ${APP_DOMAIN} www.${APP_DOMAIN} static.${APP_DOMAIN};

    location /.well-known/acme-challenge/ {
        resolver 127.0.0.11;
        # `certbot` is name of acme.sh service container
        set $upstream_certbot certbot;
        proxy_pass http://$upstream_certbot;       
    }

    location / {
        return 301 https://$server_name$request_uri;
    }
}
```

nginx and acme.sh shares `ssl` directory. Nginx watch file changes and reload its configuration. While we use nginx alpine we build[ custom image](https://github.com/appwilio/nginx/blob/master/Dockerfile#L35) with `inotify-tools` and add watch script to `/docker-entrypoint.d/`

```sh
#!/bin/sh

while inotifywait "$NGINX_SSL_ROOT" -qq -e create -e modify -e move -e delete; do
  echo "Detected certificate changes"
  nginx -t && nginx -s reload
done &

exit 0
```

How add acme.sh to docker-compose config:

```yml
version: '3.7'
services: 
nginx:
    image: appwilio/nginx
    environment:
      APP_DOMAIN:
      LOADBALANCER_SUBNET: ${LOADBALANCER_SUBNET:-127.0.0.1}
    networks:
      - default
      - public
    volumes:
      - ./ssl:/etc/nginx/ssl
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=http
        - traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=80
        - traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$APP_DOMAIN`, `www.$APP_DOMAIN`, `static.$APP_DOMAIN`)
        - traefik.tcp.routers.$COMPOSE_PROJECT_NAME.rule=HostSNI(`$APP_DOMAIN`, `www.$APP_DOMAIN`, `static.$APP_DOMAIN`)
        - traefik.tcp.routers.$COMPOSE_PROJECT_NAME.entrypoints=https
        - traefik.tcp.routers.$COMPOSE_PROJECT_NAME.tls.passthrough=true
        - traefik.tcp.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=4433
        - traefik.tcp.services.$COMPOSE_PROJECT_NAME.loadbalancer.proxyprotocol.version=2
#...
  certbot:
    image: neilpang/acme.sh
    environment:
      APP_DOMAIN:
    volumes:
      - ${SSL_ACMESH_DIR:-./acmesh}:/acme.sh
      - ${SSL_DIR:-./ssl}:/ssl
    command: >
      sh -c "sleep 60 &&
      acme.sh --register-account -m $ADMIN_EMAIL &&
      acme.sh --log --issue --standalone --keylength ec-256 -d $APP_DOMAIN -d www.$APP_DOMAIN -d static.$APP_DOMAIN;
      acme.sh --install-cert --ecc -d $APP_DOMAIN --key-file /ssl/keyfile.pem --fullchain-file /ssl/fullchain.pem &&
      chgrp 101 /ssl/*.pem && chmod 640 /ssl/*.pem"
    deploy:
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=22 20 2 */2 *
        - swarm.cronjob.skip-running=true
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 12h
```
