### ISSUE TITLE
cPanel deploy bug for wildcard subdomains

### ISSUE THREAD

**Issue by jmedellinc** [acmesh-official/acme.sh#6115]
on the deploy function, on the cpanel script, the function
  uapi DomainInfo list_domains

returns the following:

```
apiversion: 3
func: list_domains
module: DomainInfo
result: 
  data: 
    addon_domains: 
      - abc.com
      - cde.com
    main_domain: abc.com
    parked_domains: []

    sub_domains: 
      - test.abc.com
      - "*.cde.com"
  errors: ~
  messages: ~
  metadata: {}

  status: 1
  warnings: ~
```

as you can see, the wildcard subdomain is between double quotes which results on the domain not being located..

That was easily fixed adding a 
`   tr -d "\""
`
to the API call on line 82
```
  #   _response=$(uapi DomainInfo list_domains)
   _response=$(uapi DomainInfo list_domains | tr -d "\"")
```

Sorry for not posting the failed command.. I made it work, am away from the machine (decided to post or i'll forget about it) and quite frankly i'm scared it might screw things up if i start fiddling with how to reproduce it - and i think the fix is pretty straightforward..

Let me know if you need me to post the messages
